---
title: "3844 Resources"
author: "Andy Lautenschlager"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Almost all of the tools below are free to use, or at least offer free trials. If you any of these resources makes your life easier, check to see if the developers accept donations. And if you can’t donate, promote!

# Video

You’ve probably heard of [iMovie](https://www.apple.com/imovie/) (Mac) and [Windows Movie Maker](https://www.microsoft.com/en-us/store/p/movie-maker-free-video-editor/9nblggh4wwjr) or [Microsoft Photos](https://www.microsoft.com/en-us/windows/photo-movie-editor) (Windows). These applications are more than sufficient for many purposes. You may already have one of them on your computer, and if not, Movie Maker/Microsoft Photos are free to download. (iMovie is affordable, too.)

But I want to focus on some resources that maybe you haven’t heard of. In some cases, I’ll also include links to tutorials.

## YouTube Creator’s Studio

The [YouTube Creator’s Studio](https://www.youtube.com/dashboard?o=U) doesn’t offer a ton of functionality, but you can trim and combine multiple videos, add transitions, and more. Best of all, you can easily incorporate clips from a large (I would assume the largest of its kind) selection of free, Creative Commons-licensed music and videos. For many projects, that’s all you need. And the process is shockingly easy.

## YouTube Recommended Upload Encoding Settings

No matter how you produce your video, if you want to post it to YouTube, try to follow [YouTube’s recommended upload encoding specifications](https://support.google.com/youtube/answer/1722171?hl=en) for best results. Your video will upload faster and look better.

## iMovie

If you have a Mac, you may already have iMovie. This application will best suit beginners. You can find tutorials via [lynda.vt.edu](http://lynda.vt.edu/).

## Movie Maker or Microsoft Photos

If you have an older version of Windows, you may have Movie Maker. Windows 10 users likely have Microsoft Photos. Either application offers beginner-level video editing. You can find tutorials via [lynda.vt.edu](http://lynda.vt.edu/).

## OpenShot Video Editor

If you don’t already have iMovie and don’t want to pay for it, [OpenShot](http://www.openshot.org/) may be a good alternative. I’ve had some problems with crashing, but if you save often, you can still produce a simple video without Blender’s learning curve. The basic interface is similar to iMovie’s or Movie Maker’s, but you may run into trouble with plugins and other scary computer issues. Google if you need help! In the meantime, [here’s a good introduction](https://www.youtube.com/watch?v=NcUS2Jt0icE).

## DaVinci Resolve

If you've already used iMovie or Movie Maker/Microsoft Photos, try DaVinci Resolve for a more advanced option. Best of all, you can [download Resolve](https://www.blackmagicdesign.com/products/davinciresolve/) for free (scroll to the bottom of the page for download link). You can find tutorials via [lynda.vt.edu](http://lynda.vt.edu/).

## Blender

This program is for power users. If you’ve already tried iMovie or Movie Maker and need something more powerful — well, you could shell out hundreds of dollars for Final Cut Pro or Adobe Premiere, or you could use [Blender](https://www.blender.org/) for free.

Blender is primarily for 3D modeling, but its video sequencer offers more power and control than any reasonable person should expect to get for free. You can fine-tune your zooms, pans, crossfades — pretty much anything you’d want to do. The downside: It is _hard_ to learn. Luckily, you can find good tutorials online. [Oliver Villar](https://www.youtube.com/watch?v=zYVZ6rtayaA) offers a crash course in Blender basics, while YouTube user [Mikeycal Meyers](https://www.youtube.com/playlist?list=PLjyuVPBuorqIhlqZtoIvnAVQ3x18sNev4) offers hours of instruction. Both options are good, but I’d recommend the latter.

Expect a steep learning curve, but also great results.

## Clip Converter

[Clip Converter](http://www.clipconverter.cc/) allows you to download videos from YouTube, Vimeo, and more. All you need is the target video’s URL. _Extremely_ useful if you need to insert a small clip of another video into your own. Just be sure to follow fair use guidelines or rely on Creative Commons-licensed videos.

## Pexels and Pixabay

I mentioned these sites in [my previous post on web development](https://medium.com/@andylaut/free-tools-for-teachers-and-students-of-writing-and-digital-media-and-or-multimodal-composition-ec7436624678#.ugjcv29ls), but [Pixabay](https://pixabay.com/) and [Pexels](https://videos.pexels.com/) host videos under CC0 (Creative Commons Zero) license, which allows users to edit and reuse the videos without attribution. Most importantly, the content on these sites is high-quality — much higher than you would expect given the price, which is zero dollars.

## Screencastify

Screencasting applications are not hard to find. Some cost money, some are totally free (or come preinstalled on your computer), and some use the “freemium” model, in which you get basic functionality for free but have to pay for advanced features. My favorite of the latter group is [Screencastify](https://www.screencastify.com/) for Google Chrome. Just turn it on when you want to start recording, turn it off when you’re done, and Screencastify will save your video to your Google Drive account. If you use a free account, Screencastify will add its logo to your screencast, but you’ll barely notice. Very, very handy.

# Audio

Want to record a podcast or audio essay? Making a video and want to add music or improve the sound quality? Either way, you’ll want a good audio editor. If you’re a Mac user, you may already have [GarageBand](http://www.apple.com/mac/garageband/) on your computer. GarageBand is perfectly sufficient for most needs, but if you don’t have GarageBand, or if you need a little more functionality, then try the resources below.

## Audacity

[Audacity](http://www.audacityteam.org/) is the best free audio editor available. It offers so many options for recording and processing your audio, you’ll probably never get around to learning them all. Autoduck, Nyquist Prompt, Paulstretch: what do they do? Are they dance moves? I have no idea! But if you need them, Audacity’s got you covered. And Audacity’s noise reduction, filters, and volume and EQ controls will make hearing the sound of your own voice more tolerable. Audacity also makes it easy to cut and stitch multiple files together and to layer tracks on top of one another.

It’s also fairly easy to start using once you understand the basic controls. Still, I’d recommend watching a few tutorials to help get you up and running. I’d start with Colin Gray’s YouTube playlist, “[Using Audacity to Create Amazing Podcasts & Audio Recordings](https://www.youtube.com/playlist?list=PLy3KiJOHvdl1epxRuzEQqjQu1V9szwqnl).” You can also find tips on [how to make your voice sound better](https://www.youtube.com/watch?v=TYF5ytMDFpA).

## Soundflower

With [Soundflower](http://manual.audacityteam.org/man/tutorial_recording_computer_playback_on_mac.html), you can record any sound your computer is outputting (including audio from YouTube or streaming audio sites) directly into Audacity. It’s not the easiest add-on to install, but once you get it working, you can easily record audio clips from around the web, then incorporate those clips into your own work, just as you might quote a source in a traditional paper.

Again, though, stay ethical: follow fair use guidelines or rely on Creative Commons-licensed audio.

## LMMS

If you want to make your own music but don’t have Garageband, try [LMMS](https://lmms.io/) (Linux Multimedia Studio). I won’t go into much detail about it, because (a) I barely know how to use it and (b) I’ll discuss some easier ways to add music to your content below, but if you’re musically inclined, you’ll find a whole community making [original music](https://lmms.io/showcase/) using this software.

## SoundCloud

You’ve likely listened to music or podcasts on [Soundcloud](https://soundcloud.com/stream) already, but you’ll find it just as easy to start uploading your own content to the platform. Just sign up and start adding your work. You can also follow other accounts, add likes and comments, repost your favorite tracks, and create playlists to broadcast your work and others’. Perhaps most importantly, you can seamlessly share your content across platforms like Facebook, Twitter, and Medium.

## Creative Commons on SoundCloud

Another great thing about SoundCloud: You can use it to find hours of [Creative Commons-licensed music](https://soundcloud.com/search?q=creative%20commons&filter.license=to_share) to edit and use in your own work. For example, check out [this mix by Dublab](https://soundcloud.com/wearecc/dublabs-cc10-mix), a non-profit radio network in Los Angeles, featuring acclaimed artists like Julia Holter and James Pants.

Just be sure to check the license of any track you want to use and follow the specifications for attribution and reuse. Give credit where credit is due!

## dig.ccMixter

SoundCloud’s Creative Commons collection is fantastic, but it’s so deep that you may struggle to find the kind of music you want. Thankfully, [dig.ccMixter](http://dig.ccmixter.org/) can help you find the best music for you. Start with [this collection of tracks for podcast creators](http://dig.ccmixter.org/podcast_music).

# Thanks and praise

Finally, let’s take a moment to appreciate — really appreciate — the fact that most of the resources above are totally free. Everything we need (aside from cameras, good microphones, and other equipment) to create professional-level content, we can acquire in less than an hour for a total of zero monies. Ha-cha-cha!

But just because these tools are free to use doesn’t mean they’re free to create or maintain. In fact, many of them are built, developed, maintained, and supported by communities of volunteers and donors. While we teachers and students aren’t known for our deep pockets, even small contributions can help. And if we can’t contribute even a few dollars, we can at least express our thanks and spread the word.

So thank you, developers and donors; thank you, tutorial and user document creators; and thank you, everyone who uses these tools to do some good in the world.